[package]
name = "empd"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.21", features = ["derive"] }
owo-colors = "3.5.0"

[profile.release]
codegen-units = 1
lto = true
strip = true
