[package]
name = "empd"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.13", features = ["derive"] }
owo-colors = "4.0.0"

[profile.release]
codegen-units = 1
lto = true
strip = true
